package io.github.jenyaatnow.validator4j.core;

import lombok.NonNull;

import java.util.Arrays;
import java.util.Collection;
import java.util.function.Consumer;
import java.util.stream.Collectors;

/**
 * This class is the top in the inheritance hierarchy of V-classes. Each autogenerated {@code VUserDefinedClass}
 * transitively inherits this class. It contains a basic functionality to provide validation capabilities
 * for all inheritors.
 *
 * @param <TARGET> type of validated value.
 */
public abstract class ValidatableReference<TARGET> {

    /**
     * Root validation object property path constant.
     */
    protected static final String PATH_ROOT = "";

    /**
     * Path of property represented by instance of this class.
     */
    protected final String path;

    /**
     * Validated value itself.
     */
    protected final TARGET value;

    /**
     * Validation errors container.
     */
    final ErrorsCollector errors;

    /**
     * Validation rule actions prepared to perform deferred validation.
     */
    final Collection<Runnable> ruleActions;

    /**
     * Operation that uses in order to reject invalid value and put {@link ValidationError} to errors container.
     */
    private final Consumer<String> reject;

    protected ValidatableReference(@NonNull final String path,
                                   final TARGET value,
                                   @NonNull final ValidationContext ctx)
    {
        this.path = path;
        this.value = value;
        this.errors = ctx.getErrors();
        this.ruleActions = ctx.getRuleActions();

        this.reject = message -> {
            final var error = ValidationError.of(path, message);
            this.errors.add(error);
        };
    }

    /**
     * Prepares validation rules to perform deferred validation. Doesn't perform any validation itself. Example:
     *     <pre>
     *     {@code
     *     final VUser vUser = ...;
     *     vUser.getId().validate((id, reject) -> {
     *         if (id < 1) {
     *             reject.accept("Id should be positive number");
     *         }
     *     })
     *     }
     *     </pre>
     *
     * @param validationRules validation rules.
     */
    @SafeVarargs
    public final void validate(@NonNull final ValidationRule<TARGET>... validationRules) {
        final var actions = Arrays.stream(validationRules)
            .<Runnable>map(rule -> () -> rule.validate(value, reject))
            .collect(Collectors.toList());

        ruleActions.addAll(actions);
    }
}
