image: openjdk:11


stages:
  - assemble
  - check


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle


cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches


assemble:
  stage: assemble
  script:
    - ./gradlew assemble
  only:
    - branches
    - merge_requests


checkstyle:
  stage: check
  script:
    - ./gradlew checkstyleMain
    - ./gradlew checkstyleTest
  only:
    - branches
    - merge_requests


test:
  stage: check
  script:
    - ./gradlew test --console=verbose
  artifacts:
    reports:
      junit: validator4j-*/build/test-results/test/TEST-*.xml
  only:
    - branches
    - merge_requests
